insert into customers (customer_id, first_name, last_name, address, phone, email) values (1, 'Elijah', 'SmileCare', '82 Cody Alley', '901-572-7021', 'Elijah1@SmileCare.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (2, 'James', 'HappyBite', '61151 Caliangt Terrace', '682-684-3162', 'James2@HappyBite.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (3, 'Nora', 'PureOralHealth', '6 Village Terrace', '774-823-3640', 'Nora3@PureOralHealth.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (4, 'Ahmed', 'HappyBite', '5674 Gale Point', '642-324-6265', 'Ahmed4@HappyBite.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (5, 'Yasmin', 'WhiteCrownClinic', '879 Lien Place', '640-866-7324', 'Yasmin5@WhiteCrownClinic.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (6, 'Leo', 'OralHub', '923 Maple Parkway', '680-212-9006', 'Leo6@OralHub.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (7, 'Ethan', 'DentalPro', '6 Cascade Avenue', '674-898-6324', 'Ethan7@DentalPro.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (8, 'Emily', 'PureOralHealth', '25 Lake View Alley', '642-696-3313', 'Emily8@PureOralHealth.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (9, 'Olivia', 'DentalPro', '827 Marcy Plaza', '950-310-4707', 'Olivia9@DentalPro.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (10, 'Amira', 'DentalPro', '6 Petterle Center', '975-701-4850', 'Amira10@DentalPro.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (11, 'Mason', 'PearlClinic', '43206 Golf Course Alley', '532-851-8284', 'Mason11@PearlClinic.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (12, 'Noah', 'EverSmile', '151 Alpine Avenue', '825-116-7369', 'Noah12@EverSmile.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (13, 'Michael', 'PrimeDental', '7784 Talisman Road', '918-962-1835', 'Michael13@PrimeDental.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (14, 'Lucas', 'TotalDental', '53549 3rd Terrace', '615-338-1403', 'Lucas14@TotalDental.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (15, 'Liam', 'ProDentCare', '7407 Northland Center', '959-426-5812', 'Liam15@ProDentCare.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (16, 'Sofia', 'FamilyToothCare', '0 Dakota Plaza', '406-821-4207', 'Sofia16@FamilyToothCare.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (17, 'Emily', 'OralWorks', '22 Tennyson Road', '144-799-2687', 'Emily17@OralWorks.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (18, 'Daniel', 'ZenSmileStudio', '802 Marcy Junction', '630-895-3873', 'Daniel18@ZenSmileStudio.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (19, 'Mason', 'ZenSmileStudio', '3674 Maple Junction', '542-899-8685', 'Mason19@ZenSmileStudio.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (20, 'Aisha', 'BrightDental', '808 Commercial Center', '860-457-8229', 'Aisha20@BrightDental.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (21, 'Sebastian', 'TotalDental', '6904 Goodland Road', '345-241-5016', 'Sebastian21@TotalDental.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (22, 'Michael', 'IvorySmiles', '73 Schurz Park', '662-425-6155', 'Michael22@IvorySmiles.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (23, 'James', 'WhiteCrownClinic', '4324 Sherman Alley', '726-406-7167', 'James23@WhiteCrownClinic.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (24, 'Chloe', 'WhiteningWorks', '0 Corry Trail', '957-599-2998', 'Chloe24@WhiteningWorks.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (25, 'Elijah', 'WhiteCrownClinic', '1419 Helena Street', '446-170-5672', 'Elijah25@WhiteCrownClinic.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (26, 'Amira', 'OralWorks', '77190 Susan Center', '542-993-4480', 'Amira26@OralWorks.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (27, 'Nora', 'PearlClinic', '3279 Mosinee Crossing', '692-834-7443', 'Nora27@PearlClinic.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (28, 'Amira', 'PureOralHealth', '025 Truax Road', '652-764-7539', 'Amira28@PureOralHealth.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (29, 'Daniel', 'DentalPro', '5 Pennsylvania Circle', '312-996-0078', 'Daniel29@DentalPro.com');
insert into customers (customer_id, first_name, last_name, address, phone, email) values (30, 'Isaac', 'DentalPro', '0 Mariners Cove Way', '827-259-2922', 'Isaac30@DentalPro.com');
