insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (1, 'Vacuum Mixer – Tabletop', 2, 7, 97.88, 47);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (2, 'Digital Apex Locator', 6, 8, 229.35, 166);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (3, 'Gauze Sponges – 4x4” Sterile', 3, 10, 179.24, 71);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (4, 'Latex Powder-Free Gloves – Medium', 5, 6, 879.39, 177);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (5, 'Mouth Props – Autoclavable Silicone', 3, 3, 414.39, 107);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (6, 'Root Canal Files – 21mm', 4, 4, 276.08, 114);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (7, 'Ultrasonic Scaler – Multi-tip', 1, 5, 322.52, 51);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (8, 'Mixing Tips – Automix', 3, 4, 641.15, 148);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (9, 'Fluoride Varnish – Mint', 4, 8, 335.07, 181);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (10, 'Portable X-Ray Imaging Unit', 3, 5, 625.31, 145);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (11, 'Mouth Props – Autoclavable Silicone', 3, 1, 759.7, 151);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (12, 'Rubber Dams – Medium Green', 4, 1, 777.78, 50);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (13, 'Root Canal Files – 21mm', 4, 6, 126.49, 179);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (14, 'High-Speed Air Turbine Handpiece', 2, 8, 638.86, 23);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (15, 'Mouth Mirrors – Front Surface #5', 1, 8, 907.13, 126);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (16, 'Protective Eyewear – Anti-Fog', 6, 8, 818.48, 34);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (17, 'Root Canal Files – 21mm', 4, 10, 373.14, 104);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (18, 'Dental Chair Headrest Cushion', 5, 7, 385.45, 60);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (19, 'Latex Powder-Free Gloves – Medium', 6, 7, 23.74, 121);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (20, 'LED Headlamp for Loupe Mounting', 5, 8, 125.15, 138);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (21, 'Cotton Rolls – Pack of 2000', 2, 6, 59.39, 55);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (22, 'Tooth Extraction Forceps – Set of 6', 4, 9, 46.92, 189);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (23, 'Autoclave Tape – High Temp', 1, 3, 180.62, 192);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (24, 'Rubber Dams – Medium Green', 6, 8, 848.5, 72);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (25, 'High-Speed Air Turbine Handpiece', 2, 6, 540.93, 55);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (26, 'Bite Blocks – Large Size', 6, 10, 535.01, 89);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (27, 'Alginate Impression Material – Fast Set', 5, 3, 898.76, 164);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (28, 'Cheek Retractors – Adult Size', 3, 9, 765.18, 102);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (29, 'Gauze Sponges – 4x4” Sterile', 4, 5, 269.32, 199);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (30, 'Intraoral Camera HD', 2, 2, 789.69, 125);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (31, 'Mouth Mirrors – Front Surface #5', 5, 8, 641.28, 46);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (32, 'Periosteal Elevator – Stainless Steel', 2, 4, 180.02, 26);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (33, 'Assistant''s Stool – Adjustable Height', 3, 10, 617.45, 176);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (34, 'Dental Matrix Bands – Pre-cut', 4, 4, 444.11, 114);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (35, 'Intraoral Camera HD', 4, 3, 951.69, 71);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (36, 'Composite Filling Material – A2 Shade', 2, 10, 693.03, 76);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (37, 'Size 25', 3, 7, 408.24, 63);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (38, 'Tooth Extraction Forceps – Set of 6', 3, 1, 533.1, 45);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (39, 'Mouth Props – Autoclavable Silicone', 5, 1, 559.3, 86);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (40, 'Disposable Saliva Ejectors – Pack of 100', 2, 3, 386.51, 30);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (41, 'Fluoride Varnish – Mint', 3, 7, 718.11, 79);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (42, 'Intraoral Camera HD', 2, 7, 200.95, 192);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (43, 'LED Headlamp for Loupe Mounting', 2, 7, 221.68, 161);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (44, 'Disposable Mixing Pads – Non-Stick', 3, 2, 946.86, 112);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (45, 'Size 25', 5, 10, 598.91, 41);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (46, 'Latex Powder-Free Gloves – Medium', 6, 10, 630.49, 122);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (47, 'Zinc Oxide Eugenol Temporary Cement', 5, 1, 876.96, 104);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (48, 'Tooth Extraction Forceps – Set of 6', 4, 1, 897.4, 58);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (49, 'Dental Bibs – Assorted Colours', 4, 4, 282.02, 166);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (50, 'Cotton Rolls – Pack of 2000', 5, 7, 385.11, 49);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (51, 'Autoclave Tape – High Temp', 5, 6, 331.9, 28);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (52, 'Mixing Tips – Automix', 4, 10, 370.49, 65);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (53, 'Sterilization Pouches – 5.25 x 10 inch', 1, 2, 554.17, 120);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (54, 'Autoclave Tape – High Temp', 2, 6, 44.88, 97);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (55, 'Ultrasonic Scaler – Multi-tip', 4, 5, 162.47, 121);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (56, 'Fluoride Varnish – Mint', 2, 6, 116.94, 154);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (57, 'Disposable Saliva Ejectors – Pack of 100', 4, 7, 762.81, 37);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (58, 'Portable X-Ray Imaging Unit', 4, 6, 146.58, 77);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (59, 'Etching Gel – 37% Phosphoric Acid', 6, 4, 573.3, 156);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (60, 'Dental Chair Headrest Cushion', 6, 7, 989.71, 155);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (61, 'High-Speed Air Turbine Handpiece', 1, 3, 590.48, 165);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (62, 'Aspirating Syringe – Autoclavable', 2, 6, 658.11, 48);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (63, 'Disposable Gowns – Level 2', 1, 7, 105.3, 174);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (64, 'Gauze Sponges – 4x4” Sterile', 5, 2, 250.13, 136);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (65, 'Aspirating Syringe – Autoclavable', 3, 9, 604.5, 30);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (66, 'Amalgam Carrier – Stainless Steel', 5, 5, 909.68, 178);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (67, 'Sterilization Cassette – 10 Instrument', 1, 1, 586.73, 22);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (68, 'Disposable Saliva Ejectors – Pack of 100', 6, 1, 171.58, 140);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (69, 'Periosteal Elevator – Stainless Steel', 6, 10, 863.21, 191);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (70, 'Amalgam Carrier – Stainless Steel', 4, 9, 511.61, 149);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (71, 'Cotton Rolls – Pack of 2000', 6, 2, 619.85, 9);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (72, 'Disposable Air Water Syringe Tips', 3, 7, 528.21, 121);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (73, 'Disposable Saliva Ejectors – Pack of 100', 1, 10, 146.55, 147);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (74, 'Oral Suction Tubing – Universal', 2, 9, 332.17, 114);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (75, 'Composite Filling Material – A2 Shade', 5, 9, 388.23, 166);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (76, 'Tooth Extraction Forceps – Set of 6', 2, 6, 145.02, 193);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (77, 'Latex Powder-Free Gloves – Medium', 6, 8, 19.47, 186);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (78, 'Root Canal Files – 21mm', 5, 8, 892.49, 133);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (79, 'Protective Eyewear – Anti-Fog', 1, 4, 726.05, 57);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (80, 'Temporary Crown Material – Automix', 5, 5, 506.58, 44);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (81, 'Fluoride Varnish – Mint', 3, 3, 659.08, 5);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (82, 'Temporary Crown Material – Automix', 2, 7, 846.67, 93);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (83, 'Dental Dam Clamps – Assorted Sizes', 5, 8, 604.37, 38);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (84, 'Blue', 5, 9, 991.59, 54);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (85, 'Mouth Props – Autoclavable Silicone', 2, 3, 818.33, 143);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (86, 'Nitrile Gloves – Large', 1, 10, 994.99, 34);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (87, 'Protective Eyewear – Anti-Fog', 4, 2, 458.65, 135);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (88, 'Zinc Oxide Eugenol Temporary Cement', 2, 10, 751.43, 52);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (89, 'Disposable Saliva Ejectors – Pack of 100', 3, 4, 957.5, 8);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (90, 'Bonding Agent – Light Cure', 1, 5, 120.22, 135);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (91, 'Dental Matrix Bands – Pre-cut', 2, 8, 625.61, 199);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (92, 'Sterilization Cassette – 10 Instrument', 2, 8, 481.09, 55);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (93, 'Vacuum Mixer – Tabletop', 5, 8, 900.44, 47);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (94, 'Syringes – 3ml Disposable', 6, 5, 290.27, 23);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (95, 'Intraoral Camera HD', 1, 2, 653.93, 185);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (96, 'Ultrasonic Scaler – Multi-tip', 5, 3, 319.92, 90);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (97, 'Disposable Gowns – Level 2', 2, 10, 98.9, 168);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (98, 'Bite Blocks – Large Size', 2, 4, 905.99, 52);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (99, 'Ergonomic Dental Chair Pro-X', 2, 8, 979.83, 91);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (100, 'Syringes – 3ml Disposable', 1, 2, 517.88, 192);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (101, 'Etching Gel – 37% Phosphoric Acid', 1, 5, 247.73, 72);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (102, 'Gauze Sponges – 4x4” Sterile', 4, 8, 380.77, 66);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (103, 'Disposable Gowns – Level 2', 2, 3, 564.46, 112);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (104, 'Sterilization Cassette – 10 Instrument', 4, 8, 149.65, 106);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (105, 'Aspirating Syringe – Autoclavable', 6, 8, 727.89, 189);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (106, 'Protective Eyewear – Anti-Fog', 4, 8, 548.12, 13);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (107, 'LED Operatory Light – Ceiling Mount', 3, 7, 43.07, 59);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (108, 'Cotton Rolls – Pack of 2000', 4, 1, 684.91, 153);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (109, 'Mouth Mirrors – Front Surface #5', 4, 9, 450.0, 66);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (110, 'Sterilization Cassette – 10 Instrument', 4, 6, 187.48, 124);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (111, 'Bonding Agent – Light Cure', 1, 5, 722.23, 7);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (112, 'Composite Filling Material – A2 Shade', 5, 4, 591.61, 22);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (113, 'Sterilization Pouches – 5.25 x 10 inch', 4, 9, 625.57, 46);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (114, 'LED Operatory Light – Ceiling Mount', 3, 8, 942.95, 193);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (115, 'Oral Suction Tubing – Universal', 6, 3, 451.49, 41);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (116, 'Amalgam Carrier – Stainless Steel', 4, 6, 257.29, 35);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (117, 'Syringes – 3ml Disposable', 4, 1, 488.23, 8);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (118, 'Rubber Dams – Medium Green', 6, 1, 368.81, 185);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (119, 'Disposable Air Water Syringe Tips', 2, 2, 681.4, 22);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (120, 'Amalgam Carrier – Stainless Steel', 1, 3, 827.23, 151);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (121, 'Gauze Sponges – 4x4” Sterile', 4, 9, 787.06, 40);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (122, 'Disposable Saliva Ejectors – Pack of 100', 3, 5, 299.31, 80);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (123, 'Sterilization Pouches – 5.25 x 10 inch', 2, 6, 704.68, 18);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (124, 'Blue', 6, 7, 967.15, 166);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (125, 'Protective Eyewear – Anti-Fog', 4, 5, 763.36, 64);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (126, 'Size 25', 6, 7, 757.12, 5);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (127, 'Glass Ionomer Cement Kit', 3, 2, 907.26, 93);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (128, 'Root Canal Files – 21mm', 1, 5, 235.66, 153);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (129, 'Etching Gel – 37% Phosphoric Acid', 1, 3, 243.62, 117);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (130, 'Nitrile Gloves – Large', 6, 1, 420.61, 64);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (131, 'Assistant''s Stool – Adjustable Height', 5, 3, 306.22, 49);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (132, 'Composite Filling Material – A2 Shade', 3, 5, 337.75, 130);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (133, 'Mouth Props – Autoclavable Silicone', 2, 10, 797.76, 14);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (134, 'Blue', 5, 2, 73.49, 191);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (135, 'Amalgam Carrier – Stainless Steel', 4, 5, 374.16, 164);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (136, 'Ergonomic Dental Chair Pro-X', 1, 8, 718.31, 94);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (137, 'Rubber Dams – Medium Green', 6, 2, 266.56, 61);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (138, 'Mouth Props – Autoclavable Silicone', 1, 6, 341.15, 130);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (139, 'LED Headlamp for Loupe Mounting', 6, 2, 36.51, 142);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (140, 'Zinc Oxide Eugenol Temporary Cement', 4, 6, 112.76, 151);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (141, 'LED Headlamp for Loupe Mounting', 2, 2, 705.72, 4);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (142, 'Intraoral Camera HD', 1, 7, 459.69, 182);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (143, 'Zinc Oxide Eugenol Temporary Cement', 3, 1, 898.45, 154);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (144, 'Gauze Sponges – 4x4” Sterile', 3, 10, 208.64, 96);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (145, 'Protective Eyewear – Anti-Fog', 4, 1, 411.76, 67);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (146, 'Tooth Extraction Forceps – Set of 6', 1, 9, 899.21, 114);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (147, 'Disposable Air Water Syringe Tips', 4, 4, 538.58, 180);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (148, 'Dental Chair Headrest Cushion', 5, 9, 374.13, 122);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (149, 'Composite Filling Material – A2 Shade', 1, 7, 438.54, 95);
insert into stocks (stock_id, product_name, category_id, supplier_id, price, quantity_in_stock) values (150, 'Dental Matrix Bands – Pre-cut', 1, 7, 120.05, 199);
